server:
  port: 8081
spring:
  application:
    name: hzdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hzdp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.238.133
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.haizi.entity # 别名扫描包
logging:
  level:
    com.haizi: debug